### ISSUE TITLE
How to add a listener by event?

### ISSUE THREAD

**Issue by JianiYang** [matfish2/vue-formular#16]
I want to add a check to make sure user will save before exit.
And I found that there is a vue-formular.change event might be useful , but i can't use it as a common VUE
event .Is there any samples to use a event ?

**Comment by JianiYang** [comment]
Is there any way that can watch when the from's item value been changed?

**Comment by matfish2** [comment]
_As documented_ you can listen to a change event on any field. Say your field name is `title`:

```js
this.$on('vue-formular.change::title', function(data) {

});
```

**Comment by JianiYang** [comment]
thanks ,but I want to know that how can I listen all sub-item of the from or I need to add the function one by one ?

**Comment by matfish2** [comment]
Again, as documented, you can use the global `vue-formular.change` event, which is emitted for any field.
