### ISSUE TITLE
v-date can not disabled?

### ISSUE THREAD

**Issue by JianiYang** [matfish2/vue-formular#17]
when I want to add the attribute disabled to a v-date , it can still be a white blank . No matter I set it by html or js ,it might give the user a wrong info . Is there a way to change the css ?

**Comment by JianiYang** [comment]
It seems worked in the demo ,but when I trying to use it in my project ,there is a "moment is not defined".I tried to add a require as 
```
require(['vue', 'text', 'vuex', 'vueresource', 'moment', 'store'], function () {
	require(['vueformular'],function(){
```
but not work QAQ

**Comment by matfish2** [comment]
moment should be available **globally**

`window.moment = require('moment');`

**Comment by JianiYang** [comment]
Uncaught TypeError: moment(...).format is not a function(…)

It still failure whit the 
`window.moment = require(['moment']);`
