### ISSUE TITLE
Integration with v-model

### ISSUE THREAD

**Issue by rkrishnamoorthy** [matfish2/vue-formular#6]
Hi
Thanks for this component. Love the ease of use.
But how do you integrate it with v-model ?

Cheers, rk

**Comment by matfish2** [comment]
V-model is already integrated into each of the fields as their value. To programatically manipulate it use setValue. To get the value simply get the value prop off the field. Assign a v-ref to the field to access its methods and props

Sent from my Samsung device

-------- Original message --------

**Comment by rkrishnamoorthy** [comment]
What i meant was with Vue's two-way binding framework. I cant specify on
the tag a v-model attribute

**Comment by matfish2** [comment]
As I already explained `v-model` is set inside each field's template.
You can't set a v-model on anything other than form inputs (https://vuejs.org/guide/forms.html).
The `value` prop is serving the same purpose of `v-model`.
