### ISSUE TITLE
how to get programmatically if form has validation errors

### ISSUE THREAD

**Issue by rkrishnamoorthy** [matfish2/vue-formular#8]
Hi
I have a question. I would like to disable the submit button on a form if the form has errors. But i would like to do it based on a computed field which looks at the field and also a values of a few other fields and then indicates whether the submit button should be enabled

```

computed: {
    canSubmit: function() {
        // how do i check here whether form has validation errors based on rules defined for fields ?
    }

}
```

**Comment by matfish2** [comment]
Find the form instance using `v-ref`, and check the length of the `errors` property.

```
 canSubmit: function() {
      return !this.$refs.form.errors.length;
 }

```

I plan to add an `hasErrors`or `isValid` method to do the same.

**Comment by rkrishnamoorthy** [comment]
Thank you ! worked perfectly
