### ISSUE TITLE
additionalPayload doesn't respect change

### ISSUE THREAD

**Issue by purepear** [matfish2/vue-formular#9]
I didn't find how to add `type="hidden"` fields so i used `additionalPayload` but it seems it doesn't respect the change. Submits the initial value `options: {additionalPayload: {additional: 'initial value' }}`

If i change it in a method `this.options.additionalPayload.additional = 'asdsasds'` it submits 'inital value'
Also tried with `this.$set('options.additionalPayload', {additional: 'asdasdasd'}`

**Comment by purepear** [comment]
I managed to change it using `this.$refs.form.options.additionalPayload.additional = 'adasdasd'`. Is this how it's supposed to work ?

**Comment by matfish2** [comment]
Yes. You need to get the component instance, not the root one.
